### PR TITLE
remove libecl from buildsystem, jenkins and packaging

### PR DESCRIPTION
**Pull request by akva2**
Please merge this into your branch, then hold the merge in opm-common so I can test the various jenkins builds beforehand.

### CODE REVIEW

**Comment by bska** [comment]
How about the various libecl-related conditionals in `CMakeLists_files.txt`?  Do you need to make any changes there too?

**Comment by akva2** [comment]
you mean the ECL_INPUT and ECL_OUTPUT ones? they are mostly historic relics from a time when we had a dev that absolutely did not want to link his simulators to any libraries.

they are not dependent on libecl, as such. think of them as enabling/disable the old opm-output and opm-parser modules.

**Comment by akva2** [comment]
(i plan to propose their removal, but it's a separate thing)

**Comment by bska** [comment]
> you mean the ECL_INPUT and ECL_OUTPUT ones?

Yes, I did mean those.

> they are not dependent on libecl, as such. think of them as enabling/disable the old opm-output and opm-parser modules.

Okay.  I just wanted to make sure that dropping libecl doesn't turn them into unconditional "False" values which would mean dropping large fractions of the code in opm-common.

> i plan to propose their removal, but it's a separate thing

Noted.

**Pull request merged**
